### ISSUE TITLE
Je ne peut pas merge pour récupérer ta correction de mon issue avant d'avoir géré le conflit 

### ISSUE THREAD

**Issue by Staelion** [Staelion/Song-Flow#11]
Je sais pas quoi faire sur la page de conflit vu que je doit modifier le code aparament mais si je me trompe ca va casser ce que ta fait je suppose 

![image](https://user-images.githubusercontent.com/127593721/231149011-12a0e680-98a0-4c2e-89f4-b42bfbb75f85.png)

**Comment by CinquinAndy** [comment]
j'ai fait la correction dans une autre Merge request tout à l'heure, on prendra le temps de te montrer comment gérer les conflits la prochaine réunion ;p
