### ISSUE TITLE
Front position d'éléments flex box

### ISSUE THREAD

**Issue by Staelion** [Staelion/Song-Flow#13]
Comme tu pourra le voir sur les screens le truc me fait de la D et envoie mon texte hors de l'écran plutot que dans une boite comme je demande avec mon code, alaide

![image](https://user-images.githubusercontent.com/127593721/232435909-9a6b0498-9f71-436c-9da9-8a7856c0dfb8.png)
![image](https://user-images.githubusercontent.com/127593721/232436255-534b6465-8179-446c-a8cb-0cecc92f1449.png)
![image](https://user-images.githubusercontent.com/127593721/232436357-569c4829-6a4a-45ee-8fef-509038177ca2.png)

**Comment by CinquinAndy** [comment]
Lorsque tu prends des valeurs avec des % de screens ( vw - vh ) tu te met par rapport à la taille de l'écran & pas par rapport à la taille de ton container parent, 

Pour régler ton problème, tu peux mettre un w-full par exemple

(je te fais un exemple & un test)
