### ISSUE TITLE
Création nouvelle branche sur Git Kraken

### ISSUE THREAD

**Issue by Staelion** [Staelion/Song-Flow#17]
yo les potes alors p'tite question comment je fais pour créer une nouvelle branche parallèle afin de commencer une nouvelle page de login client, en sachant que j'ai déjà la page parallèle de la landing page qui n'est pas tout a fait terminé donc pas encore merge a la branche principale "V2 de la mort qui tue".

Vous avez peut-être pas accès aux branches et a mon kraken vu que c'est en local donc maybe m'expliquer direct en voc si possible sinon ici

**Comment by CinquinAndy** [comment]
![image](https://github.com/Staelion/Song-Flow/assets/55706543/79128fcb-2c7e-45fd-b464-4a606910feb5)
 ça peut par exemple ressembler à ça
