### ISSUE TITLE
back slash en trop dans le footer

### ISSUE THREAD

**Issue by LightInn** [Staelion/Song-Flow#28]
![image](https://github.com/Staelion/Song-Flow/assets/28759336/bddddffc-de3c-437f-844e-4863a95f0411)

**Comment by Staelion** [comment]
Je n'ai pas ce souci la moi j'ai checké sur toute mes pages ? 
bizzare 
![image](https://github.com/Staelion/Song-Flow/assets/127593721/41df36c4-68ff-42b5-9f67-52afbef96b57)
